version: "3.7"
services:
  netbox-sd:
    build: ..
    environment:
      NETBOX_SD_URL: https://netboxdemo.com
      NETBOX_SD_TOKEN:  72830d67beff4ae178b94d8f781842408df8069d
      NETBOX_SD_FILE_PATH: /data/netbox/netbox.json
      NETBOX_SD_LOG_LEVEL: "DEBUG"
      NETBOX_SD_VERIFY_SSL: "FALSE"
    volumes:
      - "netbox-sd-data:/data/netbox"

  prometheus:
    image: "prom/prometheus:v2.17.1"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - "netbox-sd-data:/data/netbox"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

volumes:
  netbox-sd-data: