# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  ##########################
  # Prometheus server metrics
  #########################
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  ##########################
  # Node Exporter
  ##########################
  - job_name: "node-exporter"
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - /data/netbox/netbox.json
        refresh_interval: 10s
    relabel_configs:
      # keep all targets labeled with __meta_netbox_service_node_exporter
      - source_labels: [__meta_netbox_service_node_exporter]
        action: keep
        regex: .+
      # Relabel to exporter port 9100
      - source_labels: ["__meta_netbox_name"]
        target_label: "__address__"
        replacement: "${1}:9100"

  ##########################
  # Netbox
  ##########################
  - job_name: "netbox"
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - /data/netbox/netbox.json
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_netbox_service_netbox]
        action: keep
        regex: .+
      # Relabel to exporter port 443
      - source_labels: ["__meta_netbox_name"]
        target_label: "__address__"
        replacement: "${1}:443"
      - source_labels: [__meta_netbox_tag_system]
        target_label: system
      - source_labels: [__meta_netbox_tenant]
        target_label: tenant
